#!/bin/bash
# Guards the initramfs configuration that decides whether the deployed system can find its
# own root device.
#
# WHY THIS EXISTS
#
# The bootstrap root is /dev/md3 -- an md array over NVMe. Reaching it needs THREE
# separate things, and this project has now confused them with each other once, at the cost
# of a deployment that hung after "loading initial ramdisk ..." with no output at all:
#
#   1. the raid1 DRIVER, shipped by MODULES=(nvme raid1) in the deploy hook
#   2. an ASSEMBLY step, which is the mdadm_udev HOOK -- a driver is not assembly
#   3. the array NAMES, pinned by /etc/mdadm.conf, because /etc/fstab says /dev/md2 and
#      /dev/md3 and an array that comes up as md126 does not mount
#
# The hook had (1) and not (2) or (3), and because (1) looked like the fix, the gap was
# invisible in the logs: mkinitcpio -P succeeded, the initramfs grew, and the machine still
# could not boot. A green build is not evidence here, so the configuration is asserted.
#
# Usage: test/initramfs-test.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
PROVISION="$REPO/build_archlinux/provision.sh"

PASS=0
FAIL=0
check() { # check <description> <expected> <actual>
    if [ "$2" = "$3" ]; then
        printf '  ok    %s\n' "$1"
        PASS=$((PASS + 1))
    else
        printf '  FAIL  %s\n         expected: %s\n         actual:   %s\n' "$1" "$2" "$3"
        FAIL=$((FAIL + 1))
    fi
}

# The HOOKS= line provision.sh installs into the bootstrap image.
# The HOOKS= assignment lives inside a `sed -i 's/^HOOKS=.*/HOOKS=(...)/' command, so it is
# not at the start of the line. Matching the parenthesised list itself is what works --
# and the pattern must be anchored enough to catch a genuinely empty result, which is how
# the first version of this test passed four assertions against nothing at all.
bootstrap_hooks="$(grep -oE 'HOOKS=\([^)]*\)' "$PROVISION" | head -1)"

if [ -z "$bootstrap_hooks" ]; then
    echo "FATAL: could not find the bootstrap HOOKS= assignment in $PROVISION" >&2
    exit 1
fi

echo "bootstrap initramfs hooks:"
echo "    $bootstrap_hooks"
echo

echo "(1) the driver and (2) the assembly step are different things"
check "mdadm_udev hook present (assembles the array)" \
    "yes" "$(case "$bootstrap_hooks" in *mdadm_udev*) echo yes ;; *) echo no ;; esac)"
check "block hook present (block layer)" \
    "yes" "$(case "$bootstrap_hooks" in *block*) echo yes ;; *) echo no ;; esac)"
check "filesystems hook present" \
    "yes" "$(case "$bootstrap_hooks" in *filesystems*) echo yes ;; *) echo no ;; esac)"
check "systemd hook present (this is a systemd initramfs)" \
    "yes" "$(case "$bootstrap_hooks" in *systemd*) echo yes ;; *) echo no ;; esac)"
check "no busybox 'net' hook (conflicts with systemd)" \
    "no" "$(case "$bootstrap_hooks" in *' net '*) echo yes ;; *) echo no ;; esac)"

echo
echo "the deploy hook must also (3) pin the array names and rebuild"

# The hook body is a quoted heredoc inside provision.sh.
hook_body="$(awk "/^cat > \/root\/\.ovh\/make_image_bootable\.sh <</{f=1;next} /^HOOK\$/{f=0} f" "$PROVISION")"

if [ -z "$hook_body" ]; then
    echo "FATAL: could not extract the deploy hook from $PROVISION" >&2
    exit 1
fi

check "hook ships the raid1 driver via MODULES" \
    "yes" "$(case "$hook_body" in *'MODULES=(nvme raid1)'*) echo yes ;; *) echo no ;; esac)"
check "hook writes /etc/mdadm.conf" \
    "yes" "$(case "$hook_body" in *'mdadm --detail --scan'*) echo yes ;; *) echo no ;; esac)"
check "hook rebuilds the initramfs" \
    "yes" "$(case "$hook_body" in *'mkinitcpio -P'*) echo yes ;; *) echo no ;; esac)"

# Order matters: mdadm.conf has to exist BEFORE the rebuild, or the rebuilt initramfs does
# not contain it and the names stay unpinned.
scan_line=$(printf '%s\n' "$hook_body" | grep -n 'mdadm --detail --scan' | head -1 | cut -d: -f1)
rebuild_line=$(printf '%s\n' "$hook_body" | grep -n 'mkinitcpio -P' | head -1 | cut -d: -f1)

check "mdadm.conf is written BEFORE the initramfs rebuild" \
    "yes" "$([ -n "$scan_line" ] && [ -n "$rebuild_line" ] && [ "$scan_line" -lt "$rebuild_line" ] && echo yes || echo no)"

echo
echo "the installed system's own initramfs (generated by the installer, not the image)"
check "installer uses mdadm_udev for the encrypted root" \
    "yes" "$(grep -q 'mdadm_udev' "$REPO/build_archlinux/files/cmesh-byol-install" && echo yes || echo no)"
check "installer uses sd-encrypt (reads crypttab, supports TPM2)" \
    "yes" "$(grep -q 'sd-encrypt' "$REPO/build_archlinux/files/cmesh-byol-install" && echo yes || echo no)"

echo
echo "passed: $PASS  failed: $FAIL"
[ "$FAIL" -eq 0 ]
